#!/bin/bash

DIR=$(cd $(dirname $0);pwd)

for i in .bash_profile .bashrc .vim .vimrc .gitconfig .gemrc .tmux.conf
do
  if [ ! -f "$HOME/$i" -a ! -d "$HOME/$i" ];then
    ln -s "$DIR/$i" "$HOME"
  fi
done
